### PR TITLE
Improved README and added requirements.txt for *nix-based systems.

### PR DESCRIPTION
**Pull request by josefdlange**
LMK if anything doesn't appear up to snuff...

### CODE REVIEW

**Comment by qguv** [comment]
There's also an issue with futil on non-Windows platforms. Perhaps you could add some try/except logic for futil to your PR? Something like [this](https://github.com/qguv/conspeech/commit/10ea63b6a244996be61b6cecc9b5a5ed2756956b)?

**Comment by qguv** [comment]
Also: this PR as currently written appears to fix #4.

**Comment by josefdlange** [comment]
The `requirements.txt` version locking to `scipy==0.16.1` actually makes the import work just fine for me. I don't think it's necessarily a Windows/*nix issues as much as there's been a newer version of `scipy` (`0.17.0`) that removes the module (`futil`).

**Comment by qguv** [comment]
Okay, if I have time, I'll make a PR that uses the latest scipy, but that ought to stay separate from Windows/Unix issues. Thanks for the hint.

**Comment by josefdlange** [comment]
Closing this old PR because I don't want to see it on my Github dashboard.

**Pull request closed without merging**
